// AUTO-GENERATED from bespotender category_mapping_plan.md.
// Maps a 2merkato raw category name (lowercased) -> our super-category slug.
export const RAW_TO_SUPER: Record<string, string> = {
  "construction": "construction-engineering",
  "construction and water works": "construction-engineering",
  "sewerage": "construction-engineering",
  "water engineering machinery and equipment": "construction-engineering",
  "water well drilling": "construction-engineering",
  "water pipes and fittings": "construction-engineering",
  "building and finishing materials": "construction-engineering",
  "contract administration and supervision": "construction-engineering",
  "construction machinery and equipment": "construction-engineering",
  "building construction": "construction-engineering",
  "road and bridge construction": "construction-engineering",
  "water system installation": "construction-engineering",
  "water well and pool cleaning": "construction-engineering",
  "architectural and construction design": "construction-engineering",
  "water construction": "construction-engineering",
  "irrigation works": "construction-engineering",
  "finishig works": "construction-engineering",
  "water proofing works": "construction-engineering",
  "geotechnical investigation & laboratory testing": "construction-engineering",
  "sanitary and ceramics": "construction-engineering",
  "software supply and development and web design": "ict-telecom",
  "it and telecom": "ict-telecom",
  "telecommunication equipment": "ict-telecom",
  "software provision, development and web design": "ict-telecom",
  "networking equipment and installation": "ict-telecom",
  "computer and accessories": "ict-telecom",
  "telecommunication service": "ict-telecom",
  "ict (consultancy)": "ict-telecom",
  "health care": "medical-health-pharma",
  "health care, medical industry": "medical-health-pharma",
  "medical equipment and supplies": "medical-health-pharma",
  "health related services and materials": "medical-health-pharma",
  "pharmaceutical products": "medical-health-pharma",
  "veterinary equipment and supplies": "medical-health-pharma",
  "health related (consultancy)": "medical-health-pharma",
  "agriculture and farming": "agriculture-farming",
  "live animals": "agriculture-farming",
  "products and services (agriculture)": "agriculture-farming",
  "flora and horticulture": "agriculture-farming",
  "animal feed": "agriculture-farming",
  "poultry, bee and animal husbandry": "agriculture-farming",
  "pesticides, insecticides and herbicides": "agriculture-farming",
  "agricultural (consultancy)": "agriculture-farming",
  "industrial machinery provision and installation": "manufacturing-machinery",
  "mechanical": "manufacturing-machinery",
  "machinery": "manufacturing-machinery",
  "installation, maintenance and other engineering services": "manufacturing-machinery",
  "hand tools and workshop equipment": "manufacturing-machinery",
  "plastic raw materials and products": "manufacturing-machinery",
  "plastic products": "manufacturing-machinery",
  "plastic raw materials": "manufacturing-machinery",
  "packaging and labelling": "manufacturing-machinery",
  "wood and wood working": "manufacturing-machinery",
  "test & measurement tools": "manufacturing-machinery",
  "vehicles and spare parts": "vehicles-transport-logistics",
  "vehicles purchase": "vehicles-transport-logistics",
  "tri wheeler, motorcycles and bicycles purchase": "vehicles-transport-logistics",
  "spare parts and car decoration materials": "vehicles-transport-logistics",
  "warehousing, transit and transport service": "vehicles-transport-logistics",
  "warehouse and storage service": "vehicles-transport-logistics",
  "transit, customs clearing, packing and forwarding": "vehicles-transport-logistics",
  "freight transport": "vehicles-transport-logistics",
  "air cargo service": "vehicles-transport-logistics",
  "transportation service": "vehicles-transport-logistics",
  "vehicle (garage service)": "vehicles-transport-logistics",
  "electrical, electromechanical and electronics": "electrical-energy-power",
  "pumps, motors and compressors": "electrical-energy-power",
  "energy, power and electricity": "electrical-energy-power",
  "generators": "electrical-energy-power",
  "solar and photovoltaic": "electrical-energy-power",
  "coal": "electrical-energy-power",
  "firewood": "electrical-energy-power",
  "hydro power": "electrical-energy-power",
  "fuel and lubricants": "electrical-energy-power",
  "air conditioning and refrigeration": "electrical-energy-power",
  "accounting and auditing": "business-finance-services",
  "accounting": "business-finance-services",
  "accounting system design": "business-finance-services",
  "banking equipment and services": "business-finance-services",
  "insurance service": "business-finance-services",
  "consultancy": "business-finance-services",
  "financial (consultancy)": "business-finance-services",
  "legal (consultancy)": "business-finance-services",
  "organizational (consultancy)": "business-finance-services",
  "government treasury bill": "business-finance-services",
  "quality assurance services": "business-finance-services",
  "translation, editing and writing": "business-finance-services",
  "advertising and promotion": "marketing-advertising-events",
  "event organizing and planning": "marketing-advertising-events",
  "public relations": "marketing-advertising-events",
  "promotional items": "marketing-advertising-events",
  "graphic design": "marketing-advertising-events",
  "billboards and digital advertising": "marketing-advertising-events",
  "printed advertising materials": "marketing-advertising-events",
  "public address systems": "marketing-advertising-events",
  "printing and publishing": "marketing-advertising-events",
  "office supplies and services": "office-education-stationery",
  "office machines and accessories": "office-education-stationery",
  "stationery": "office-education-stationery",
  "office machines and computers": "office-education-stationery",
  "secretarial service": "office-education-stationery",
  "education and training": "office-education-stationery",
  "academic (consultancy)": "office-education-stationery",
  "furniture and furnishing": "household-furniture-furnishings",
  "home appliance and supplies": "household-furniture-furnishings",
  "carpets and curtains": "household-furniture-furnishings",
  "house furniture": "household-furniture-furnishings",
  "office furniture": "household-furniture-furnishings",
  "interior design service and material": "household-furniture-furnishings",
  "kitchen equipment": "household-furniture-furnishings",
  "foam mattress": "household-furniture-furnishings",
  "textile, garment and leather": "clothing-textiles-personal-care",
  "shoes and other leather products": "clothing-textiles-personal-care",
  "textile, garments and uniforms": "clothing-textiles-personal-care",
  "personal care products and services": "clothing-textiles-personal-care",
  "sport materials and equipment": "clothing-textiles-personal-care",
  "tents and camping equipment": "clothing-textiles-personal-care",
  "food and beverage": "hospitality-food-beverages",
  "food items and drinks": "hospitality-food-beverages",
  "hospitality, tour and travel": "hospitality-food-beverages",
  "tour and travel": "hospitality-food-beverages",
  "air ticket": "hospitality-food-beverages",
  "hotel service provision": "hospitality-food-beverages",
  "catering and cafeteria services": "hospitality-food-beverages",
  "land lease & real estate": "real-estate-facilities-maintenance",
  "rent": "real-estate-facilities-maintenance",
  "house, building and warehouse": "real-estate-facilities-maintenance",
  "gardening and landscaping": "real-estate-facilities-maintenance",
  "cleaning and janitorial equipment and service": "real-estate-facilities-maintenance",
  "maintenance and repair": "real-estate-facilities-maintenance",
  "pest control and fumigants": "real-estate-facilities-maintenance",
  "pest control and fumigation": "real-estate-facilities-maintenance",
  "chemicals and reagents": "raw-materials-chemicals-metals",
  "laboratory equipment and chemicals": "raw-materials-chemicals-metals",
  "steel, metals and aluminium": "raw-materials-chemicals-metals",
  "steel raw materials and products": "raw-materials-chemicals-metals",
  "aluminium products": "raw-materials-chemicals-metals",
  "aluminium works and installation": "raw-materials-chemicals-metals",
  "other metals": "raw-materials-chemicals-metals",
  "metal and metal working": "raw-materials-chemicals-metals",
  "mineral and natural resources": "raw-materials-chemicals-metals",
  "raw materials": "raw-materials-chemicals-metals",
  "sales, disposals and foreclosure": "sales-disposals-privatization",
  "vehicle and machinery sale": "sales-disposals-privatization",
  "house and building sale": "sales-disposals-privatization",
  "business, industry and factory foreclosure": "sales-disposals-privatization",
  "vehicle and machinery foreclosure": "sales-disposals-privatization",
  "house and building foreclosure": "sales-disposals-privatization",
  "shares and others foreclosure": "sales-disposals-privatization",
  "disposal sale": "sales-disposals-privatization",
  "other sales": "sales-disposals-privatization",
  "privatization": "sales-disposals-privatization",
  "disposal of hazardous waste": "sales-disposals-privatization",
  "general service provision": "general-services-misc",
  "courier services": "general-services-misc",
  "distribution of different products": "general-services-misc",
  "art": "general-services-misc",
  "fine art, antiques, crafts": "general-services-misc",
  "audio visual, photography and filming service and equipment": "general-services-misc",
  "music and entertainment": "general-services-misc",
  "musical instruments": "general-services-misc",
  "humanitarian aid supply, relief items": "general-services-misc",
  "labour outsourcing services": "general-services-misc",
  "safety and security": "general-services-misc",
  "equipment (safety)": "general-services-misc",
  "social and public policy (consultancy)": "general-services-misc",
  "environmental (consultancy)": "general-services-misc",
  "consumable goods": "general-services-misc",
  "others": "general-services-misc",
};

// Manual overrides for live 2merkato category names not in the mapping plan.
// Kept separate so regenerating RAW_TO_SUPER won't drop them. Keys are
// lowercased and whitespace-collapsed.
export const MANUAL_OVERRIDES: Record<string, string> = {
  "equipment and accessories": "manufacturing-machinery",
  equipment: "manufacturing-machinery",
  "raw materials and supplies": "raw-materials-chemicals-metals",
  materials: "raw-materials-chemicals-metals",
  other: "general-services-misc",
  services: "general-services-misc",
  "products and services": "general-services-misc",
  "social and public policy": "general-services-misc",
  environmental: "general-services-misc",
  organizational: "business-finance-services",
  financial: "business-finance-services",
  legal: "business-finance-services",
  "accounting and auditing": "business-finance-services",
  "accounting system design": "business-finance-services",
  "accounting and auditing, accounting system design": "business-finance-services",
  "health related": "medical-health-pharma",
  ict: "ict-telecom",
  "telecommunication equipment": "ict-telecom",
  "house and building": "real-estate-facilities-maintenance",
};

// Resolve a 2merkato category name to a super-category slug (or null if unmapped).
export function toSuperSlug(rawName: string | null | undefined): string | null {
  if (!rawName) return null;
  const key = rawName.trim().toLowerCase().replace(/\s+/g, " ");
  return MANUAL_OVERRIDES[key] ?? RAW_TO_SUPER[key] ?? null;
}
