-- Qellal — 0009 invoicing (Slice 3)
-- Invoice records + line items. Amounts in ETB. NO payment processing — invoices
-- are generated by lifecycle actions in test mode; in production the gateway
-- (via service role) would create/settle them.

create table if not exists invoices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  number text not null,
  status text not null default 'open'
    check (status in ('draft', 'open', 'paid', 'void', 'credit')),
  currency text not null default 'ETB',
  total numeric(10, 2) not null default 0,
  period_start timestamptz,
  period_end timestamptz,
  issued_at timestamptz default now(),
  paid_at timestamptz,
  created_at timestamptz default now()
);
create index if not exists invoices_user_idx on invoices (user_id, created_at desc);

create table if not exists invoice_lines (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  description text not null,
  amount numeric(10, 2) not null default 0, -- negative = credit / proration
  created_at timestamptz default now()
);

alter table invoices enable row level security;
alter table invoice_lines enable row level security;

-- Users read/generate own invoices (test mode; production would restrict writes
-- to the service role). Staff/admin see all.
drop policy if exists invoices_own_all on invoices;
create policy invoices_own_all on invoices
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists invoices_staff_all on invoices;
create policy invoices_staff_all on invoices
  for all
  using (public.current_user_role() in ('staff', 'admin'))
  with check (public.current_user_role() in ('staff', 'admin'));

drop policy if exists invoice_lines_own_all on invoice_lines;
create policy invoice_lines_own_all on invoice_lines
  for all
  using (exists (select 1 from invoices i where i.id = invoice_id and i.user_id = auth.uid()))
  with check (exists (select 1 from invoices i where i.id = invoice_id and i.user_id = auth.uid()));
drop policy if exists invoice_lines_staff_all on invoice_lines;
create policy invoice_lines_staff_all on invoice_lines
  for all
  using (public.current_user_role() in ('staff', 'admin'))
  with check (public.current_user_role() in ('staff', 'admin'));
