-- 0017: Seed 2merkato's official category taxonomy (from /api/v1/categories).
-- 66 parents + subcategories = 175 distinct. Upsert by slug so
-- existing tender links are preserved; the scraper still auto-creates new ones.
insert into public.categories (name, slug) values
  ('Accounting and Auditing, Accounting System Design', 'accounting-and-auditing-accounting-system-design'),
  ('Advertising and Promotion', 'advertising-and-promotion'),
  ('Event Organizing and Planning', 'event-organizing-and-planning'),
  ('Public Relations', 'public-relations'),
  ('Promotional Items', 'promotional-items'),
  ('Graphic Design', 'graphic-design'),
  ('Billboards and Digital Advertising', 'billboards-and-digital-advertising'),
  ('Printed Advertising Materials', 'printed-advertising-materials'),
  ('Public Address Systems', 'public-address-systems'),
  ('Agriculture and Farming', 'agriculture-and-farming'),
  ('Live Animals', 'live-animals'),
  ('Machinery and Equipment', 'machinery-and-equipment'),
  ('Products and Services', 'products-and-services'),
  ('Raw Materials and Supplies', 'raw-materials-and-supplies'),
  ('Flora and Horticulture', 'flora-and-horticulture'),
  ('Animal Feed', 'animal-feed'),
  ('Poultry, Bee and Animal Husbandry', 'poultry-bee-and-animal-husbandry'),
  ('Air conditioning and Refrigeration', 'air-conditioning-and-refrigeration'),
  ('Art', 'art'),
  ('Audio Visual, Photography and Filming Service and Equipment', 'audio-visual-photography-and-filming-service-and-equipment'),
  ('Music and Entertainment', 'music-and-entertainment'),
  ('Fine Art, Antiques, Crafts', 'fine-art-antiques-crafts'),
  ('Musical Instruments', 'musical-instruments'),
  ('Banking Equipment and Services', 'banking-equipment-and-services'),
  ('Catering and Cafeteria Services', 'catering-and-cafeteria-services'),
  ('Chemicals and Reagents', 'chemicals-and-reagents'),
  ('Cleaning and Janitorial Equipment and Service', 'cleaning-and-janitorial-equipment-and-service'),
  ('Construction and Water Works', 'construction-and-water-works'),
  ('Sewerage', 'sewerage'),
  ('Water Engineering Machinery and Equipment', 'water-engineering-machinery-and-equipment'),
  ('Water Well Drilling', 'water-well-drilling'),
  ('Water Pipes and Fittings', 'water-pipes-and-fittings'),
  ('Building and Finishing Materials', 'building-and-finishing-materials'),
  ('Contract Administration and Supervision', 'contract-administration-and-supervision'),
  ('Construction Machinery and Equipment', 'construction-machinery-and-equipment'),
  ('Building Construction', 'building-construction'),
  ('Road and Bridge Construction', 'road-and-bridge-construction'),
  ('Water System Installation', 'water-system-installation'),
  ('Water Well and Pool Cleaning', 'water-well-and-pool-cleaning'),
  ('Architectural and Construction Design', 'architectural-and-construction-design'),
  ('Water Construction', 'water-construction'),
  ('Irrigation Works', 'irrigation-works'),
  ('Finishig Works', 'finishig-works'),
  ('Water Proofing Works', 'water-proofing-works'),
  ('Consultancy', 'consultancy'),
  ('Other', 'other'),
  ('ICT', 'ict'),
  ('Health Related', 'health-related'),
  ('Engineering', 'engineering'),
  ('Financial', 'financial'),
  ('Legal', 'legal'),
  ('Academic', 'academic'),
  ('Organizational', 'organizational'),
  ('Social and Public Policy', 'social-and-public-policy'),
  ('Agricultural', 'agricultural'),
  ('Environmental', 'environmental'),
  ('Consumable Goods', 'consumable-goods'),
  ('Courier Services', 'courier-services'),
  ('Distribution of Different products', 'distribution-of-different-products'),
  ('Education and Training', 'education-and-training'),
  ('Materials', 'materials'),
  ('Services', 'services'),
  ('Electrical, Electromechanical and Electronics', 'electrical-electromechanical-and-electronics'),
  ('Installation, Maintenance and Other Engineering Services', 'installation-maintenance-and-other-engineering-services'),
  ('Equipment and Accessories', 'equipment-and-accessories'),
  ('Pumps, Motors and Compressors', 'pumps-motors-and-compressors'),
  ('Energy, Power and Electricity', 'energy-power-and-electricity'),
  ('Generators', 'generators'),
  ('Solar and Photovoltaic', 'solar-and-photovoltaic'),
  ('Coal', 'coal'),
  ('Firewood', 'firewood'),
  ('Hydro Power', 'hydro-power'),
  ('Food and Beverage', 'food-and-beverage'),
  ('Food Items and Drinks', 'food-items-and-drinks'),
  ('Fuel and Lubricants', 'fuel-and-lubricants'),
  ('Furniture and Furnishing', 'furniture-and-furnishing'),
  ('Home Appliance and Supplies', 'home-appliance-and-supplies'),
  ('House Furniture', 'house-furniture'),
  ('Office Furniture', 'office-furniture'),
  ('Carpets and Curtains', 'carpets-and-curtains'),
  ('Gardening and Landscaping', 'gardening-and-landscaping'),
  ('General Service Provision', 'general-service-provision'),
  ('Geotechnical Investigation & Laboratory Testing', 'geotechnical-investigation-laboratory-testing'),
  ('Government Treasury Bill', 'government-treasury-bill'),
  ('Hand Tools and Workshop Equipment', 'hand-tools-and-workshop-equipment'),
  ('Health Care, Medical Industry', 'health-care-medical-industry'),
  ('Medical Equipment and Supplies', 'medical-equipment-and-supplies'),
  ('Health Related Services and Materials', 'health-related-services-and-materials'),
  ('Pharmaceutical Products', 'pharmaceutical-products'),
  ('Veterinary Equipment and Supplies', 'veterinary-equipment-and-supplies'),
  ('Hospitality, Tour and Travel', 'hospitality-tour-and-travel'),
  ('Tour and Travel', 'tour-and-travel'),
  ('Air Ticket', 'air-ticket'),
  ('Hotel Service Provision', 'hotel-service-provision'),
  ('Humanitarian Aid Supply, Relief Items', 'humanitarian-aid-supply-relief-items'),
  ('Industrial Machinery Provision and Installation', 'industrial-machinery-provision-and-installation'),
  ('Insurance Service', 'insurance-service'),
  ('Interior Design Service and Material', 'interior-design-service-and-material'),
  ('IT and Telecom', 'it-and-telecom'),
  ('Telecommunication  Equipment', 'telecommunication-equipment'),
  ('Software Provision, Development and Web Design', 'software-provision-development-and-web-design'),
  ('Networking Equipment and Installation', 'networking-equipment-and-installation'),
  ('Computer and Accessories', 'computer-and-accessories'),
  ('Telecommunication Service', 'telecommunication-service'),
  ('Kitchen Equipment', 'kitchen-equipment'),
  ('Laboratory Equipment and Chemicals', 'laboratory-equipment-and-chemicals'),
  ('Labour Outsourcing Services', 'labour-outsourcing-services'),
  ('Land Lease & Real Estate', 'land-lease-real-estate'),
  ('Maintenance and Repair', 'maintenance-and-repair'),
  ('Others', 'others'),
  ('Machinery', 'machinery'),
  ('Vehicle (garage service)', 'vehicle-garage-service'),
  ('Furniture', 'furniture'),
  ('House and Building', 'house-and-building'),
  ('Office Machines and Computers', 'office-machines-and-computers'),
  ('Mechanical', 'mechanical'),
  ('Metal and Metal Working', 'metal-and-metal-working'),
  ('Mineral and Natural Resources', 'mineral-and-natural-resources'),
  ('Office Supplies and Services', 'office-supplies-and-services'),
  ('Office Machines and Accessories', 'office-machines-and-accessories'),
  ('Stationery', 'stationery'),
  ('Secretarial Service', 'secretarial-service'),
  ('Packaging and Labelling', 'packaging-and-labelling'),
  ('Personal Care Products and Services', 'personal-care-products-and-services'),
  ('Pest Control and Fumigants', 'pest-control-and-fumigants'),
  ('Pesticides, Insecticides and Herbicides', 'pesticides-insecticides-and-herbicides'),
  ('Pest Control and Fumigation', 'pest-control-and-fumigation'),
  ('Plastic Raw Materials and Products', 'plastic-raw-materials-and-products'),
  ('Foam Mattress', 'foam-mattress'),
  ('Plastic Products', 'plastic-products'),
  ('Plastic Raw Materials', 'plastic-raw-materials'),
  ('Printing and Publishing', 'printing-and-publishing'),
  ('Privatization', 'privatization'),
  ('Quality Assurance Services', 'quality-assurance-services'),
  ('Raw materials', 'raw-materials'),
  ('Rent', 'rent'),
  ('Construction Machinery', 'construction-machinery'),
  ('Vehicle', 'vehicle'),
  ('House, Building and Warehouse', 'house-building-and-warehouse'),
  ('Safety and Security', 'safety-and-security'),
  ('Service', 'service'),
  ('Equipment', 'equipment'),
  ('Disposal of Hazardous Waste', 'disposal-of-hazardous-waste'),
  ('Sales, Disposals and Foreclosure', 'sales-disposals-and-foreclosure'),
  ('Disposal Sale', 'disposal-sale'),
  ('Other Sales', 'other-sales'),
  ('Vehicle and Machinery Sale', 'vehicle-and-machinery-sale'),
  ('House and Building Sale', 'house-and-building-sale'),
  ('Business, Industry and Factory Foreclosure', 'business-industry-and-factory-foreclosure'),
  ('Vehicle and Machinery Foreclosure', 'vehicle-and-machinery-foreclosure'),
  ('House and Building Foreclosure', 'house-and-building-foreclosure'),
  ('Shares and Others Foreclosure', 'shares-and-others-foreclosure'),
  ('Sanitary and Ceramics', 'sanitary-and-ceramics'),
  ('Spare Parts and Car Decoration Materials', 'spare-parts-and-car-decoration-materials'),
  ('Sport Materials and Equipment', 'sport-materials-and-equipment'),
  ('Steel, Metals and Aluminium', 'steel-metals-and-aluminium'),
  ('Steel Raw Materials and Products', 'steel-raw-materials-and-products'),
  ('Aluminium Products', 'aluminium-products'),
  ('Aluminium Works and Installation', 'aluminium-works-and-installation'),
  ('Other Metals', 'other-metals'),
  ('Tents and Camping Equipment', 'tents-and-camping-equipment'),
  ('Test & Measurement Tools', 'test-measurement-tools'),
  ('Textile, Garment and Leather', 'textile-garment-and-leather'),
  ('Shoes and Other Leather Products', 'shoes-and-other-leather-products'),
  ('Textile, Garments and Uniforms', 'textile-garments-and-uniforms'),
  ('Translation, Editing and Writing', 'translation-editing-and-writing'),
  ('Tri Wheeler, Motorcycles and Bicycles Purchase', 'tri-wheeler-motorcycles-and-bicycles-purchase'),
  ('Vehicles Purchase', 'vehicles-purchase'),
  ('Warehousing, Transit and Transport Service', 'warehousing-transit-and-transport-service'),
  ('Warehouse and Storage Service', 'warehouse-and-storage-service'),
  ('Transit, Customs Clearing, Packing and Forwarding', 'transit-customs-clearing-packing-and-forwarding'),
  ('Freight Transport', 'freight-transport'),
  ('Air Cargo Service', 'air-cargo-service'),
  ('Transportation Service', 'transportation-service'),
  ('Wood and Wood Working', 'wood-and-wood-working')
on conflict (slug) do nothing;
